syntax = "proto3";
package streaming;

service StreamingService {
  rpc ListarUsuarios (Empty) returns (UsuarioList);
  rpc ListarMusicas (Empty) returns (MusicaList);
  rpc ListarPlaylistsDoUsuario (IdRequest) returns (PlaylistList);
  rpc ListarMusicasDaPlaylist (IdRequest) returns (MusicaList);
  rpc ListarPlaylistsComMusica (IdRequest) returns (PlaylistList);
}

message Empty {}

message IdRequest {
  int32 id = 1;
}

message Usuario {
  int32 id = 1;
  string nome = 2;
  int32 idade = 3;
}

message Musica {
  int32 id = 1;
  string nome = 2;
  string artista = 3;
}

message Playlist {
  int32 id = 1;
  string nome = 2;
  int32 usuario_id = 3;
}

message UsuarioList { repeated Usuario usuarios = 1; }
message MusicaList { repeated Musica musicas = 1; }
message PlaylistList { repeated Playlist playlists = 1; }