# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarUsuarios = channel.unary_unary(
                '/streaming.StreamingService/ListarUsuarios',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.UsuarioList.FromString,
                _registered_method=True)
        self.ListarMusicas = channel.unary_unary(
                '/streaming.StreamingService/ListarMusicas',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.MusicaList.FromString,
                _registered_method=True)
        self.ListarPlaylistsDoUsuario = channel.unary_unary(
                '/streaming.StreamingService/ListarPlaylistsDoUsuario',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.ListarMusicasDaPlaylist = channel.unary_unary(
                '/streaming.StreamingService/ListarMusicasDaPlaylist',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.MusicaList.FromString,
                _registered_method=True)
        self.ListarPlaylistsComMusica = channel.unary_unary(
                '/streaming.StreamingService/ListarPlaylistsComMusica',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.PlaylistList.FromString,
                _registered_method=True)


class StreamingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMusicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylistsDoUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMusicasDaPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylistsComMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarUsuarios,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.UsuarioList.SerializeToString,
            ),
            'ListarMusicas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarMusicas,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.MusicaList.SerializeToString,
            ),
            'ListarPlaylistsDoUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPlaylistsDoUsuario,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.PlaylistList.SerializeToString,
            ),
            'ListarMusicasDaPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarMusicasDaPlaylist,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.MusicaList.SerializeToString,
            ),
            'ListarPlaylistsComMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPlaylistsComMusica,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.PlaylistList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.StreamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarUsuarios',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.UsuarioList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarMusicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarMusicas',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.MusicaList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPlaylistsDoUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarPlaylistsDoUsuario',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarMusicasDaPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarMusicasDaPlaylist',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.MusicaList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPlaylistsComMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarPlaylistsComMusica',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
