# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"\x07\n\x05\x45mpty\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05idade\x18\x03 \x01(\x05\"3\n\x06Musica\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07\x61rtista\x18\x03 \x01(\t\"8\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x12\n\nusuario_id\x18\x03 \x01(\x05\"3\n\x0bUsuarioList\x12$\n\x08usuarios\x18\x01 \x03(\x0b\x32\x12.streaming.Usuario\"0\n\nMusicaList\x12\"\n\x07musicas\x18\x01 \x03(\x0b\x32\x11.streaming.Musica\"6\n\x0cPlaylistList\x12&\n\tplaylists\x18\x01 \x03(\x0b\x32\x13.streaming.Playlist2\xe6\x02\n\x10StreamingService\x12:\n\x0eListarUsuarios\x12\x10.streaming.Empty\x1a\x16.streaming.UsuarioList\x12\x38\n\rListarMusicas\x12\x10.streaming.Empty\x1a\x15.streaming.MusicaList\x12I\n\x18ListarPlaylistsDoUsuario\x12\x14.streaming.IdRequest\x1a\x17.streaming.PlaylistList\x12\x46\n\x17ListarMusicasDaPlaylist\x12\x14.streaming.IdRequest\x1a\x15.streaming.MusicaList\x12I\n\x18ListarPlaylistsComMusica\x12\x14.streaming.IdRequest\x1a\x17.streaming.PlaylistListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_IDREQUEST']._serialized_start=39
  _globals['_IDREQUEST']._serialized_end=62
  _globals['_USUARIO']._serialized_start=64
  _globals['_USUARIO']._serialized_end=114
  _globals['_MUSICA']._serialized_start=116
  _globals['_MUSICA']._serialized_end=167
  _globals['_PLAYLIST']._serialized_start=169
  _globals['_PLAYLIST']._serialized_end=225
  _globals['_USUARIOLIST']._serialized_start=227
  _globals['_USUARIOLIST']._serialized_end=278
  _globals['_MUSICALIST']._serialized_start=280
  _globals['_MUSICALIST']._serialized_end=328
  _globals['_PLAYLISTLIST']._serialized_start=330
  _globals['_PLAYLISTLIST']._serialized_end=384
  _globals['_STREAMINGSERVICE']._serialized_start=387
  _globals['_STREAMINGSERVICE']._serialized_end=745
# @@protoc_insertion_point(module_scope)
